### ISSUE TITLE
Demo page disagrees with library on message segment count.

### ISSUE THREAD

**Issue by scanningdeer** [TwilioDevEd/message-segment-calculator#13]
Possibly the library is out of date at https://twiliodeved.github.io/message-segment-calculator/ , it seems like characters that take 4 blocks aren't getting properly calculated to figure out the number of message segments.  

Example message: `Testing Hand 🤟🏻🤟🏻🤟🏻🤟🏻🤟🏻🤟🏻🤟🏻🤟🏻🤟🏻🤟🏻🤟🏻🤟🏻🤟🏻🤟🏻 🤟🏻`

I've pulled down and tested the playground and the demo webpage and with current commit of c74a6b235caca44a29f0f4d4ede0a8fd6e3fd8b5 everything seems to compute as expected.

**Comment by vernig** [comment]
Thanks @scanningdeer for flagging that. Let me do some investigation and get back to you shortly

**Comment by vernig** [comment]
Thanks for spotting this @scanningdeer. The issue should now be fixed. Can you try and let me know?

**Comment by scanningdeer** [comment]
It looks like it works correctly now. Thanks.
