### ISSUE TITLE
SQL version of this calculator

### ISSUE THREAD

**Issue by jbradach** [TwilioDevEd/message-segment-calculator#2]
This calculator is extremely helpful. Is there by chance a version of this in SQL? Would it be more work than it was worth to try to recreate this in SQL?

Being able to run segment counts on messages in our database would be extremely helpful.

**Comment by vernig** [comment]
@jbradach I'm afraid we don't have a version of this in SQL. We are thinking about having a distributable version of a library providing this functionality. The initial version would be inJS. You can keep track of it on #7
