### ISSUE TITLE
UCS-2 Highlighing isn't reflecting these characters correctly

### ISSUE THREAD

**Issue by alankleindev** [TwilioDevEd/message-segment-calculator#28]
I̳F̳ Y̳O̳U̳ P̳R̳E̳F̳E̳R̳

The above text requires UCS-2 but it isn't properly reflected in the Segments section of the tool to highlight these are the characters causing the use of UCS-2 over GSM-7.

The tool does properly reflected that encoding is UCS-2.

**Comment by vdupin** [comment]
Hello,

Is there a problem with the SegmentedMessage class ?

The following results are the same:

- `new SegmentedMessage(TEXT_WITH_400_CHARACTERS, 'UCS-2').segmentsCount`
- `new SegmentedMessage(TEXT_WITH_400_CHARACTERS, 'GSM-7').segmentsCount`

I couldn't force encoding :/

Thank you !

**Comment by hughrawlinson** [comment]
Thanks! This is resolved in the latest release
