### ISSUE TITLE
License for this Code?

### ISSUE THREAD

**Issue by BryceStevenWilley** [TwilioDevEd/message-segment-calculator#3]
This is a super useful tool when sending messages with Twilio, thanks for open sourcing it!

I was wondering if Twilio would consider adding a license to this code, as unlicensed code is generally still considered proprietary.  We have a similar segment counting tool in our service that uses Twilio, and it would be awesome to be able to include this authoritative source in some way in our UI.

It looks like most of the other projects under the DevEd organization are MIT licensed, but just wanted to check.

**Comment by HugoCrd** [comment]
Hi, I wrapped part of this code in an ad-hoc library that I would be glad to publicly release on NPM (and give you the appropriate credit obviously).
The only thing blocking me right now is this license problem. 
Can I help in any way? Would like me to open a PR with the MIT license used on the other TwilioDevEd repositories?

**Comment by HugoCrd** [comment]
Hi again,
I created the following PR: https://github.com/TwilioDevEd/message-segment-calculator/pull/6 in an attempt to make the maintainers' life easier. @vernig feel free to merge or close it depending on Twilio's position here.
Thanks 🙏

**Comment by vernig** [comment]
@HugoCrd and @BryceStevenWilley, thanks for your interest in this repo and the functionality provided. Out of curiosity, would you be interested in a package that provide the same functionality to be integrated in script / server side? The idea is to convert this into a npm package, and I'm wondering if there is any interest in this?

**Comment by HugoCrd** [comment]
Hi @vernig, thanks for merging #6!
To answer your question, yes we would definitely be interested in that.
We actually did it internally and published a first tool here: https://www.npmjs.com/package/@setkeeper/text-message-utils
If you plan to work on something on your side, I would definitely consider moving to your tool and remove ours from NPM as I'm sure you would have more resources to put into it.

**Comment by vernig** [comment]
Hey @HugoCrd that package is pretty good already. I see you are re-using the `segment-calculator.js` already. My idea was to move all the core of this tool into a package as you did and make it available over CDN. I'll raise a new issue in this repo, so I'll add it to my TODO list

**Comment by vernig** [comment]
Created #7 to track this enhancement
