### ISSUE TITLE
Calculator says encoding is UCS-2, but it looks like UTF-16?

### ISSUE THREAD

**Issue by ctstacey** [TwilioDevEd/message-segment-calculator#5]
**Great work! This is the best SMS segment calculator I have found on the web!**

A small point:
When I tried a few emojis like 😋 (U+1F60B) I found they seemed to encode correctly, but it looks like UTF-16.
My understanding was the UCS-2 is fixed 16-bit width, so can't encode emojis.
https://stackoverflow.com/questions/54771549/emojis-not-correctly-encode-into-hexadecimal#answer-54771717
http://www.differencebetween.net/technology/software-technology/difference-between-ucs-2-and-utf-16/

The calculator says it's using UCS-2, but is it actually using UTF-16?

(happy to submit pull requests, just asking for clarification before taking any actions)

**Comment by ValZapod** [comment]
It can encode emojis. For example, try to send this to your friend.

**Comment by ctstacey** [comment]
If the coding is actually UTF-16 (for code points outside the BMP), do you want the UCS-2 description changed to UFT-16?
If so, I'll submit a pull request (when time allows).

**Comment by ValZapod** [comment]
> do you want the UCS-2 description changed to UFT-16?

That is a bad idea, since UCS-2 is what is only permited still (though need to look up 5G SMS over IP specs).

**Comment by vernig** [comment]
Agree with @ValZapod. The only two encoding allowed by GSM specs are GSM7 and UCS-2. Emoji are built on top of the latter through _surrogates_. 

From the point of view of the calculator, we decided to show only GSM7 and UCS2 because the main purpose of it is to calculate how many segments are going to be sent and which encoding will be used by the carrier.

**Comment by vernig** [comment]
I'm going to close this issue unless there are other inputs. Thanks all for contributing to the conversation!

**Comment by ctstacey** [comment]
All good, again, great work on the calculator!
